name: cinematch
description: CineMatch - Flutter app conectada a TMDB
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  provider: ^6.0.5
  sqflite: ^2.2.8+3
  path: ^1.8.3
  cached_network_image: ^3.2.4
  url_launcher: ^6.1.10
  flutter_staggered_animations: ^1.1.0
  shared_preferences: ^2.1.1
  webview_flutter: ^4.0.7
  shimmer: ^2.0.0

  # Share package actualizado (versiÃ³n que incluye namespace en Android)
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/